name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build web-app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          rm -rf public
          mkdir public
          cp -r dist/* public/
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add public
          git commit -m "Deploy to GitHub Pages"
          git push origin master
